import type { DemoProject } from "./types"

// getCompanyAndHallInfoヘルパー関数のインポートが必要
// これはcontext内でのみ使用可能なので、ここでは明示的に値を設定

/**
 * 画面間データ整合性を保った包括的テストデータ
 *
 * 構成:
 * - トリニティガール (id: 1-6): 様々なキャストブッキングステータス
 * - スロセレ (id: 7-12): 様々なキャストブッキングステータス
 * - 合同抽選会 (id: 21-28): 提案前→受注→実施中→終了の各段階
 */
export const comprehensiveTestProjects: Omit<DemoProject, "companyName" | "companyId" | "hallId">[] = [
  // ======================================
  // トリニティガール商材 (id: 1-6)
  // ======================================

  // id:1 - 見積中、キャスト未選択
  {
    id: 1,
    projectNumber: "TG-001",
    projectName: "新台入替イベント",
    clientName: "マルハン渋谷店",
    date: "2026/03/15",
    venue: "1F特設ブース",
    talent: "-",
    estimateAmount: "¥650,000",
    status: "proposed",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/01",
    hallName: "マルハン渋谷店",
    projectStatus: "見積作成中",
    category: "イベント",
    eventType: "トリニティガール",
    eventProductName: "新台入替イベント",
    eventDate: "2026/03/15",
    estimatedBillingAmount: 650000,
    startTime: "11:00",
    endTime: "17:00",
    companionCount: "0",
    directorCount: "0",
    mcCount: "0",
    selectedCompanions: [],
    selectedDirectors: [],
    selectedMcs: [],
  },

  // id:2 - 受注済み、キャスト選択済み、仮押さえ依頼中（pending）
  {
    id: 2,
    projectNumber: "TG-002",
    projectName: "春の大感謝祭",
    clientName: "ダイナム新宿店",
    date: "2026/03/20",
    venue: "2F イベントスペース",
    talent: "Rio, Ayaka",
    estimateAmount: "¥720,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/05",
    hallName: "ダイナム新宿店",
    projectStatus: "仮押さえ依頼中",
    category: "イベント",
    eventType: "トリニティガール",
    eventProductName: "春の大感謝祭",
    eventDate: "2026/03/20",
    estimatedBillingAmount: 720000,
    startTime: "12:00",
    endTime: "18:00",
    companionCount: "2",
    directorCount: "1",
    mcCount: "0",
    selectedCompanions: ["Rio", "Ayaka"],
    selectedDirectors: ["田中ディレクター"],
    selectedMcs: [],
    companionBookingStatus: {
      "Rio": "pending",
      "Ayaka": "pending",
    },
    directorBookingStatus: {
      "田中ディレクター": "pending",
    },
  },

  // id:3 - 受注済み、キャスト選択済み、仮押さえ済み（tentative）
  {
    id: 3,
    projectNumber: "TG-003",
    projectName: "GW特別企画",
    clientName: "ガイア池袋店",
    date: "2026/04/29",
    venue: "エントランスホール",
    talent: "Nanaka, 山田 花子",
    estimateAmount: "¥680,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/10",
    hallName: "ガイア池袋店",
    projectStatus: "仮押さえ済み",
    category: "イベント",
    eventType: "トリニティガール",
    eventProductName: "GW特別企画",
    eventDate: "2026/04/29",
    estimatedBillingAmount: 680000,
    startTime: "10:00",
    endTime: "16:00",
    companionCount: "2",
    directorCount: "1",
    mcCount: "1",
    selectedCompanions: ["Nanaka", "山田 花子"],
    selectedDirectors: ["佐藤ディレクター"],
    selectedMcs: ["鈴木 一郎"],
    companionBookingStatus: {
      "Nanaka": "tentative",
      "山田 花子": "tentative",
    },
    directorBookingStatus: {
      "佐藤ディレクター": "tentative",
    },
    mcBookingStatus: {
      "鈴木 一郎": "tentative",
    },
  },

  // id:4 - 受注済み、キャスト選択済み、本押さえ済み（confirmed）
  {
    id: 4,
    projectNumber: "TG-004",
    projectName: "夏の大抽選会",
    clientName: "エース上野店",
    date: "2026/07/15",
    venue: "特設ステージ",
    talent: "佐藤 美咲, 鈴木 さくら",
    estimateAmount: "¥750,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/15",
    hallName: "エース上野店",
    projectStatus: "本押さえ済み",
    category: "イベント",
    eventType: "トリニティガール",
    eventProductName: "夏の大抽選会",
    eventDate: "2026/07/15",
    estimatedBillingAmount: 750000,
    startTime: "13:00",
    endTime: "19:00",
    companionCount: "2",
    directorCount: "1",
    mcCount: "1",
    selectedCompanions: ["佐藤 美咲", "鈴木 さくら"],
    selectedDirectors: ["高橋ディレクター"],
    selectedMcs: ["中村 太郎"],
    companionBookingStatus: {
      "佐藤 美咲": "confirmed",
      "鈴木 さくら": "confirmed",
    },
    directorBookingStatus: {
      "高橋ディレクター": "confirmed",
    },
    mcBookingStatus: {
      "中村 太郎": "confirmed",
    },
    companionCostumes: {
      "佐藤 美咲": "青いドレス",
      "鈴木 さくら": "赤いドレス",
    },
  },

  // id:5 - 見積中、キャスト一部選択、一部仮押さえ不可
  {
    id: 5,
    projectNumber: "TG-005",
    projectName: "秋の収穫祭",
    clientName: "サンライズ錦糸町店",
    date: "2026/09/20",
    venue: "屋外特設会場",
    talent: "高橋 みゆき",
    estimateAmount: "¥600,000",
    status: "proposed",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/20",
    hallName: "サンライズ錦糸町店",
    projectStatus: "キャスト調整中",
    category: "イベント",
    eventType: "トリニティガール",
    eventProductName: "秋の収穫祭",
    eventDate: "2026/09/20",
    estimatedBillingAmount: 600000,
    startTime: "14:00",
    endTime: "18:00",
    companionCount: "2",
    directorCount: "1",
    mcCount: "0",
    selectedCompanions: ["高橋 みゆき", "伊藤 あかり"],
    selectedDirectors: ["小林ディレクター"],
    selectedMcs: [],
    companionBookingStatus: {
      "高橋 みゆき": "tentative",
      "伊藤 あかり": "pending",
    },
    companionTentativeHoldFailureComment: {
      "伊藤 あかり": "同日に他のイベントが入っているため仮押さえできません",
    },
    directorBookingStatus: {
      "小林ディレクター": "pending",
    },
  },

  // id:6 - 受注済み、キャスト選択済み、本押さえ依頼中（confirmed_request）
  {
    id: 6,
    projectNumber: "TG-006",
    projectName: "冬のボーナスキャンペーン",
    clientName: "ビッグエース新橋店",
    date: "2026/12/10",
    venue: "メインフロア",
    talent: "Rio, Nanaka, Ayaka",
    estimateAmount: "¥850,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/25",
    hallName: "ビッグエース新橋店",
    projectStatus: "本押さえ依頼中",
    category: "イベント",
    eventType: "トリニティガール",
    eventProductName: "冬のボーナスキャンペーン",
    eventDate: "2026/12/10",
    estimatedBillingAmount: 850000,
    startTime: "11:00",
    endTime: "20:00",
    companionCount: "3",
    directorCount: "2",
    mcCount: "1",
    selectedCompanions: ["Rio", "Nanaka", "Ayaka"],
    selectedDirectors: ["田中ディレクター", "佐藤ディレクター"],
    selectedMcs: ["鈴木 一郎"],
    companionBookingStatus: {
      "Rio": "confirmed_request",
      "Nanaka": "confirmed_request",
      "Ayaka": "confirmed_request",
    },
    directorBookingStatus: {
      "田中ディレクター": "confirmed_request",
      "佐藤ディレクター": "confirmed_request",
    },
    mcBookingStatus: {
      "鈴木 一郎": "confirmed_request",
    },
  },

  // ======================================
  // スロセレ商材 (id: 7-12)
  // ======================================

  // id:7 - 見積中、キャスト未選択
  {
    id: 7,
    projectNumber: "SS-001",
    projectName: "新機種導入イベント",
    clientName: "パチンコランド横浜店",
    date: "2026/03/25",
    venue: "スロットコーナー",
    talent: "-",
    estimateAmount: "¥550,000",
    status: "proposed",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/05",
    hallName: "パチンコランド横浜店",
    projectStatus: "見積作成中",
    category: "イベント",
    eventType: "スロセレ",
    eventProductName: "新機種導入イベント",
    eventDate: "2026/03/25",
    estimatedBillingAmount: 550000,
    startTime: "15:00",
    endTime: "19:00",
    companionCount: "0",
    directorCount: "0",
    mcCount: "0",
    selectedCompanions: [],
    selectedDirectors: [],
    selectedMcs: [],
  },

  // id:8 - 受注済み、MC選択済み、仮押さえ中
  {
    id: 8,
    projectNumber: "SS-002",
    projectName: "春のスロットフェア",
    clientName: "エースパチンコ川崎店",
    date: "2026/04/10",
    venue: "スロットフロア全体",
    talent: "山本MC",
    estimateAmount: "¥480,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/10",
    hallName: "エースパチンコ川崎店",
    projectStatus: "仮押さえ済み",
    category: "イベント",
    eventType: "スロセレ",
    eventProductName: "春のスロットフェア",
    eventDate: "2026/04/10",
    estimatedBillingAmount: 480000,
    startTime: "14:00",
    endTime: "18:00",
    companionCount: "0",
    directorCount: "0",
    mcCount: "1",
    selectedCompanions: [],
    selectedDirectors: [],
    selectedMcs: ["山本MC"],
    mcBookingStatus: {
      "山本MC": "tentative",
    },
  },

  // id:9 - 受注済み、MC+ディレクター選択済み、本押さえ済み
  {
    id: 9,
    projectNumber: "SS-003",
    projectName: "GW大型イベント",
    clientName: "パチンコワールド大宮店",
    date: "2026/05/03",
    venue: "メインホール",
    talent: "田中MC, 加藤ディレクター",
    estimateAmount: "¥620,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/15",
    hallName: "パチンコワールド大宮店",
    projectStatus: "本押さえ済み",
    category: "イベント",
    eventType: "スロセレ",
    eventProductName: "GW大型イベント",
    eventDate: "2026/05/03",
    estimatedBillingAmount: 620000,
    startTime: "10:00",
    endTime: "20:00",
    companionCount: "0",
    directorCount: "1",
    mcCount: "1",
    selectedCompanions: [],
    selectedDirectors: ["加藤ディレクター"],
    selectedMcs: ["田中MC"],
    directorBookingStatus: {
      "加藤ディレクター": "confirmed",
    },
    mcBookingStatus: {
      "田中MC": "confirmed",
    },
  },

  // id:10 - 見積中、MC選択済み、仮押さえ不可あり
  {
    id: 10,
    projectNumber: "SS-004",
    projectName: "夏の大抽選会",
    clientName: "ビッグパチンコ千葉店",
    date: "2026/08/15",
    venue: "特設ステージ",
    talent: "佐々木MC",
    estimateAmount: "¥580,000",
    status: "proposed",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/20",
    hallName: "ビッグパチンコ千葉店",
    projectStatus: "キャスト調整中",
    category: "イベント",
    eventType: "スロセレ",
    eventProductName: "夏の大抽選会",
    eventDate: "2026/08/15",
    estimatedBillingAmount: 580000,
    startTime: "13:00",
    endTime: "17:00",
    companionCount: "0",
    directorCount: "0",
    mcCount: "1",
    selectedCompanions: [],
    selectedDirectors: [],
    selectedMcs: ["佐々木MC"],
    mcBookingStatus: {
      "佐々木MC": "pending",
    },
    mcTentativeHoldFailureComment: {
      "佐々木MC": "お盆休みのため対応不可",
    },
  },

  // id:11 - 受注済み、MC選択済み、仮押さえ済み
  {
    id: 11,
    projectNumber: "SS-005",
    projectName: "秋の新台入替",
    clientName: "マルハン船橋店",
    date: "2026/10/05",
    venue: "スロットエリア",
    talent: "鈴木MC",
    estimateAmount: "¥520,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/25",
    hallName: "マルハン船橋店",
    projectStatus: "仮押さえ済み",
    category: "イベント",
    eventType: "スロセレ",
    eventProductName: "秋の新台入替",
    eventDate: "2026/10/05",
    estimatedBillingAmount: 520000,
    startTime: "16:00",
    endTime: "20:00",
    companionCount: "0",
    directorCount: "0",
    mcCount: "1",
    selectedCompanions: [],
    selectedDirectors: [],
    selectedMcs: ["鈴木MC"],
    mcBookingStatus: {
      "鈴木MC": "tentative",
    },
  },

  // id:12 - 受注済み、フルキャスト、全て本押さえ済み
  {
    id: 12,
    projectNumber: "SS-006",
    projectName: "年末ビッグイベント",
    clientName: "ダイナム柏店",
    date: "2026/12/28",
    venue: "全フロア",
    talent: "高橋MC, 小林MC, 伊藤ディレクター, 渡辺ディレクター",
    estimateAmount: "¥890,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/03/01",
    hallName: "ダイナム柏店",
    projectStatus: "本押さえ済み",
    category: "イベント",
    eventType: "スロセレ",
    eventProductName: "年末ビッグイベント",
    eventDate: "2026/12/28",
    estimatedBillingAmount: 890000,
    startTime: "09:00",
    endTime: "22:00",
    companionCount: "0",
    directorCount: "2",
    mcCount: "2",
    selectedCompanions: [],
    selectedDirectors: ["伊藤ディレクター", "渡辺ディレクター"],
    selectedMcs: ["高橋MC", "小林MC"],
    directorBookingStatus: {
      "伊藤ディレクター": "confirmed",
      "渡辺ディレクター": "confirmed",
    },
    mcBookingStatus: {
      "高橋MC": "confirmed",
      "小林MC": "confirmed",
    },
  },

  // ======================================
  // 合同抽選会商材 (id: 21-28)
  // ======================================

  // id:21 - 提案前（before-proposal）、基本情報のみ
  {
    id: 21,
    projectNumber: "GL-001",
    projectName: "春の合同大抽選会（提案前）",
    clientName: "マルハン本店",
    date: "2026/03/30",
    venue: "-",
    talent: "-",
    estimateAmount: "¥0",
    status: "proposed",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/05",
    hallName: "マルハン本店",
    category: "ポイント",
    eventType: "合同抽選会",
    eventProductName: "春の合同大抽選会（提案前）",
    eventDate: "2026/03/30",
    estimatedBillingAmount: 0,
    hallNames: ["マルハン本店", "マルハン渋谷店"],
    eventStartDate: "2026/03/25",
    eventEndDate: "2026/03/30",
    area: "東京都",
    proposalStatus: "before-proposal",
    dmMailing: "no",
    budget: "¥800,000",
  },

  // id:22 - 提案中（proposing）、ヨミA、景品情報あり
  {
    id: 22,
    projectNumber: "GL-002",
    projectName: "GW特別合同抽選会",
    clientName: "ダイナム",
    date: "2026/05/05",
    venue: "-",
    talent: "-",
    estimateAmount: "¥1,200,000",
    status: "proposed",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/10",
    hallName: "ダイナム新宿店",
    category: "ポイント",
    eventType: "合同抽選会",
    eventProductName: "GW特別合同抽選会",
    eventDate: "2026/05/05",
    estimatedBillingAmount: 1200000,
    hallNames: ["ダイナム新宿店", "ダイナム池袋店", "ダイナム上野店"],
    eventStartDate: "2026/04/29",
    eventEndDate: "2026/05/06",
    area: "東京都",
    proposalStatus: "proposing",
    readingCertainty: "A",
    dmMailing: "yes",
    budget: "¥1,200,000",
    prizeInfo: [
      { rank: "特賞", name: "液晶テレビ 50インチ", quantity: "2", prizeId: "1", vendorId: "1", vendorName: "景品卸売センター" },
      { rank: "A賞", name: "ノートパソコン", quantity: "5", prizeId: "2", vendorId: "1", vendorName: "景品卸売センター" },
      { rank: "B賞", name: "クオカード 5000円分", quantity: "30", prizeId: "7", vendorId: "1", vendorName: "景品卸売センター" },
    ],
  },

  // id:23 - 提案中（proposing）、ヨミB、DM発送あり
  {
    id: 23,
    projectNumber: "GL-003",
    projectName: "夏の大感謝抽選会",
    clientName: "ガイア",
    date: "2026/07/20",
    venue: "-",
    talent: "-",
    estimateAmount: "¥950,000",
    status: "proposed",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/15",
    hallName: "ガイア池袋店",
    category: "ポイント",
    eventType: "合同抽選会",
    eventProductName: "夏の大感謝抽選会",
    eventDate: "2026/07/20",
    estimatedBillingAmount: 950000,
    hallNames: ["ガイア池袋店", "ガイア新宿店"],
    eventStartDate: "2026/07/15",
    eventEndDate: "2026/07/21",
    area: "東京都",
    proposalStatus: "proposing",
    readingCertainty: "B",
    dmMailing: "yes",
    budget: "¥950,000",
    prizeInfo: [
      { rank: "特賞", name: "電動自転車", quantity: "3", prizeId: "4", vendorId: "2", vendorName: "プライズワールド" },
      { rank: "A賞", name: "高級炊飯器", quantity: "10", prizeId: "5", vendorId: "3", vendorName: "ギフトサプライ" },
      { rank: "B賞", name: "コーヒーメーカー", quantity: "20", prizeId: "6", vendorId: "3", vendorName: "ギフトサプライ" },
    ],
  },

  // id:24 - 受注（order-received）、実施前、景品未発注、デザイン依頼なし
  {
    id: 24,
    projectNumber: "GL-004",
    projectName: "お盆特別抽選会",
    clientName: "エース",
    date: "2026/08/15",
    venue: "-",
    talent: "-",
    estimateAmount: "¥700,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/20",
    hallName: "エース上野店",
    category: "ポイント",
    eventType: "合同抽選会",
    eventProductName: "お盆特別抽選会",
    eventDate: "2026/08/15",
    estimatedBillingAmount: 700000,
    hallNames: ["エース上野店"],
    eventStartDate: "2026/08/13",
    eventEndDate: "2026/08/16",
    area: "東京都",
    proposalStatus: "order-received",
    executionStatus: "実施前",
    dmMailing: "no",
    budget: "¥700,000",
    prizeInfo: [
      { rank: "A賞", name: "掃除機ロボット", quantity: "5", prizeId: "3", vendorId: "2", vendorName: "プライズワールド" },
      { rank: "B賞", name: "クオカード 5000円分", quantity: "50", prizeId: "7", vendorId: "1", vendorName: "景品卸売センター" },
    ],
  },

  // id:25 - 受注（order-received）、実施前、ポスター依頼済み（アップロード待ち）
  {
    id: 25,
    projectNumber: "GL-005",
    projectName: "秋の合同大抽選会",
    clientName: "サンライズ",
    date: "2026/09/25",
    venue: "-",
    talent: "-",
    estimateAmount: "¥1,100,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/02/25",
    hallName: "サンライズ錦糸町店",
    category: "ポイント",
    eventType: "合同抽選会",
    eventProductName: "秋の合同大抽選会",
    eventDate: "2026/09/25",
    estimatedBillingAmount: 1100000,
    hallNames: ["サンライズ錦糸町店", "サンライズ新橋店"],
    eventStartDate: "2026/09/20",
    eventEndDate: "2026/09/26",
    area: "東京都",
    proposalStatus: "order-received",
    executionStatus: "実施前",
    dmMailing: "no",
    budget: "¥1,100,000",
    prizeInfo: [
      { rank: "特賞", name: "液晶テレビ 50インチ", quantity: "2", prizeId: "1", vendorId: "1", vendorName: "景品卸売センター" },
      { rank: "A賞", name: "ノートパソコン", quantity: "8", prizeId: "2", vendorId: "1", vendorName: "景品卸売センター" },
      { rank: "B賞", name: "高級炊飯器", quantity: "15", prizeId: "5", vendorId: "3", vendorName: "ギフトサプライ" },
      { rank: "C賞", name: "クオカード 5000円分", quantity: "100", prizeId: "7", vendorId: "1", vendorName: "景品卸売センター" },
    ],
    // ポスター依頼済み（dr-1で参照）
  },

  // id:26 - 受注（order-received）、実施前、ポスター・DM・当選通知書全て依頼済み、景品発注済み
  {
    id: 26,
    projectNumber: "GL-006",
    projectName: "年末ジャンボ抽選会",
    clientName: "ビッグエース",
    date: "2026/12/25",
    venue: "-",
    talent: "-",
    estimateAmount: "¥1,500,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2026/03/01",
    hallName: "ビッグエース新橋店",
    category: "ポイント",
    eventType: "合同抽選会",
    eventProductName: "年末ジャンボ抽選会",
    eventDate: "2026/12/25",
    estimatedBillingAmount: 1500000,
    hallNames: ["ビッグエース新橋店", "ビッグエース横浜店", "ビッグエース川崎店"],
    eventStartDate: "2026/12/20",
    eventEndDate: "2026/12/26",
    area: "東京都・神奈川県",
    proposalStatus: "order-received",
    executionStatus: "実施前",
    dmMailing: "yes",
    budget: "¥1,500,000",
    prizeInfo: [
      { rank: "特賞", name: "液晶テレビ 50インチ", quantity: "3", prizeId: "1", vendorId: "1", vendorName: "景品卸売センター" },
      { rank: "A賞", name: "ノートパソコン", quantity: "10", prizeId: "2", vendorId: "1", vendorName: "景品卸売センター" },
      { rank: "B賞", name: "掃除機ロボット", quantity: "20", prizeId: "3", vendorId: "2", vendorName: "プライズワールド" },
      { rank: "C賞", name: "クオカード 10000円分", quantity: "50", prizeId: "8", vendorId: "1", vendorName: "景品卸売センター" },
      { rank: "D賞", name: "クオカード 5000円分", quantity: "200", prizeId: "7", vendorId: "1", vendorName: "景品卸売センター" },
    ],
    prizeOrderedAt: "2026-02-12T10:00:00Z",
    prizeOrdersByVendor: [
      {
        vendorId: "1",
        vendorName: "景品卸売センター",
        requestedAt: "2026-02-12T10:00:00Z",
        document: {
          projectName: "年末ジャンボ抽選会",
          hallNames: "ビッグエース新橋店、ビッグエース横浜店、ビッグエース川崎店",
          prizeNames: "液晶テレビ 50インチ (3個)、ノートパソコン (10個)、クオカード 10000円分 (50個)、クオカード 5000円分 (200個)",
          totalQuantity: 263,
        },
      },
      {
        vendorId: "2",
        vendorName: "プライズワールド",
        requestedAt: "2026-02-12T10:00:00Z",
        document: {
          projectName: "年末ジャンボ抽選会",
          hallNames: "ビッグエース新橋店、ビッグエース横浜店、ビッグエース川崎店",
          prizeNames: "掃除機ロボット (20個)",
          totalQuantity: 20,
        },
      },
    ],
    // ポスター依頼済み（dr-2）、DM依頼済み（dr-3）、当選通知書依頼済み（dr-4）
  },

  // id:27 - 受注（order-received）、実施中、全て完了、配送情報入力中
  {
    id: 27,
    projectNumber: "GL-007",
    projectName: "新春特別抽選会",
    clientName: "パチンコランド",
    date: "2026/01/15",
    venue: "-",
    talent: "-",
    estimateAmount: "¥850,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2025/12/01",
    hallName: "パチンコランド横浜店",
    category: "ポイント",
    eventType: "合同抽選会",
    eventProductName: "新春特別抽選会",
    eventDate: "2026/01/15",
    estimatedBillingAmount: 850000,
    hallNames: ["パチンコランド横浜店", "パチンコランド川崎店"],
    eventStartDate: "2026/01/10",
    eventEndDate: "2026/01/16",
    area: "神奈川県",
    proposalStatus: "order-received",
    executionStatus: "実施中",
    dmMailing: "yes",
    budget: "¥850,000",
    prizeInfo: [
      { rank: "特賞", name: "電動自転車", quantity: "2", prizeId: "4", vendorId: "2", vendorName: "プライズワールド" },
      { rank: "A賞", name: "高級炊飯器", quantity: "10", prizeId: "5", vendorId: "3", vendorName: "ギフトサプライ" },
      { rank: "B賞", name: "コーヒーメーカー", quantity: "30", prizeId: "6", vendorId: "3", vendorName: "ギフトサプライ" },
      { rank: "C賞", name: "クオカード 5000円分", quantity: "100", prizeId: "7", vendorId: "1", vendorName: "景品卸売センター" },
    ],
    prizeOrderedAt: "2025-12-15T10:00:00Z",
    prizeOrdersByVendor: [
      {
        vendorId: "1",
        vendorName: "景品卸売センター",
        requestedAt: "2025-12-15T10:00:00Z",
        document: {
          projectName: "新春特別抽選会",
          hallNames: "パチンコランド横浜店、パチンコランド川崎店",
          prizeNames: "クオカード 5000円分 (100個)",
          totalQuantity: 100,
        },
      },
      {
        vendorId: "2",
        vendorName: "プライズワールド",
        requestedAt: "2025-12-15T10:00:00Z",
        document: {
          projectName: "新春特別抽選会",
          hallNames: "パチンコランド横浜店、パチンコランド川崎店",
          prizeNames: "電動自転車 (2個)",
          totalQuantity: 2,
        },
      },
      {
        vendorId: "3",
        vendorName: "ギフトサプライ",
        requestedAt: "2025-12-15T10:00:00Z",
        document: {
          projectName: "新春特別抽選会",
          hallNames: "パチンコランド横浜店、パチンコランド川崎店",
          prizeNames: "高級炊飯器 (10個)、コーヒーメーカー (30個)",
          totalQuantity: 40,
        },
      },
    ],
    winnerListUploadedAt: "2026-01-12T14:00:00Z",
    notificationOrderSentAt: "2026-01-13T09:00:00Z",
    // ポスター・DM・当選通知書全てアップロード済み（dr-5, dr-6, dr-7）
  },

  // id:28 - 受注（order-received）、終了、全て完了
  {
    id: 28,
    projectNumber: "GL-008",
    projectName: "冬の大感謝祭（終了）",
    clientName: "エースパチンコ",
    date: "2025/12/20",
    venue: "-",
    talent: "-",
    estimateAmount: "¥650,000",
    status: "ordered",
    salesPersonName: "山田 太郎",
    requestDate: "2025/11/01",
    hallName: "エースパチンコ川崎店",
    category: "ポイント",
    eventType: "合同抽選会",
    eventProductName: "冬の大感謝祭（終了）",
    eventDate: "2025/12/20",
    estimatedBillingAmount: 650000,
    hallNames: ["エースパチンコ川崎店"],
    eventStartDate: "2025/12/15",
    eventEndDate: "2025/12/21",
    area: "神奈川県",
    proposalStatus: "order-received",
    executionStatus: "終了",
    dmMailing: "no",
    budget: "¥650,000",
    prizeInfo: [
      { rank: "A賞", name: "掃除機ロボット", quantity: "5", prizeId: "3", vendorId: "2", vendorName: "プライズワールド" },
      { rank: "B賞", name: "コーヒーメーカー", quantity: "15", prizeId: "6", vendorId: "3", vendorName: "ギフトサプライ" },
      { rank: "C賞", name: "クオカード 5000円分", quantity: "80", prizeId: "7", vendorId: "1", vendorName: "景品卸売センター" },
    ],
    prizeOrderedAt: "2025-11-20T10:00:00Z",
    prizeOrdersByVendor: [
      {
        vendorId: "1",
        vendorName: "景品卸売センター",
        requestedAt: "2025-11-20T10:00:00Z",
        document: {
          projectName: "冬の大感謝祭（終了）",
          hallNames: "エースパチンコ川崎店",
          prizeNames: "クオカード 5000円分 (80個)",
          totalQuantity: 80,
        },
      },
      {
        vendorId: "2",
        vendorName: "プライズワールド",
        requestedAt: "2025-11-20T10:00:00Z",
        document: {
          projectName: "冬の大感謝祭（終了）",
          hallNames: "エースパチンコ川崎店",
          prizeNames: "掃除機ロボット (5個)",
          totalQuantity: 5,
        },
      },
      {
        vendorId: "3",
        vendorName: "ギフトサプライ",
        requestedAt: "2025-11-20T10:00:00Z",
        document: {
          projectName: "冬の大感謝祭（終了）",
          hallNames: "エースパチンコ川崎店",
          prizeNames: "コーヒーメーカー (15個)",
          totalQuantity: 15,
        },
      },
    ],
    winnerListUploadedAt: "2025-12-18T14:00:00Z",
    notificationOrderSentAt: "2025-12-19T09:00:00Z",
    prizeDeliveryInfoByVendor: [
      {
        vendorId: "1",
        vendorName: "景品卸売センター",
        deliveredAt: "2025-12-22T10:00:00Z",
        deliveries: [
          { winnerId: "1", winnerName: "山田太郎", carrierName: "ヤマト運輸", trackingNumber: "1234-5678-9012", shippedAt: "2025-12-22" },
          { winnerId: "2", winnerName: "佐藤花子", carrierName: "佐川急便", trackingNumber: "2345-6789-0123", shippedAt: "2025-12-22" },
        ],
      },
      {
        vendorId: "2",
        vendorName: "プライズワールド",
        deliveredAt: "2025-12-23T10:00:00Z",
        deliveries: [
          { winnerId: "3", winnerName: "鈴木一郎", carrierName: "ヤマト運輸", trackingNumber: "3456-7890-1234", shippedAt: "2025-12-23" },
        ],
      },
    ],
  },
]
